image: node
git:
  path: github.com/mephux/komanda
  branch: master
script:
  - npm install
  - npm install -g grunt-cli
  - grunt run:all
notify:
  email:
    recipients:
      - dustin.webber@gmail.com
